# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c77bfd065c8210926d0bfcf89d9bb968208c8d3a2458083711252dc25ecd669c53fd8f3a3804a06a9c199367b32ea8b97935a11069e0603685e70389ba1e37be

test:
  secret_key_base: 8ac5c0d2dee8387e1f8d0abc473c6d52a4ca3f60c172b4140358c588523cd2451b4a7273b6daf922bd71887e0c3056d7b3789d6452a32ce19129d8a04051ed9f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
